/* DO NOT EDIT THIS FILE. It is machine generated. */
/*
static char sccsid[] = "@(#)bitmaps.c	3.1";

	Copyright (c) 1986 	Chris Guthrie

Permission to use, copy, modify, and distribute this
software and its documentation for any purpose and without
fee is hereby granted, provided that the above copyright
notice appear in all copies and that both that copyright
notice and this permission notice appear in supporting
documentation.  No representations are made about the
suitability of this software for any purpose.  It is
provided "as is" without express or implied warranty.

*/

#include <X11/X.h>

/**** These are the ships ****/
#define VIEWS		16
#define ship_width	16
#define ship_height	16

/**** These are the explosions ****/

#define ex_width	64
#define ex_height	64

/**** These are the misc things ****/

#define cloud_width 7
#define cloud_height 7

#define etorp_width 3
#define etorp_height 3

#define mtorp_width 3
#define mtorp_height 3

#define crossw 15
#define crossh 15

#define crossmask_width 15
#define crossmask_height 15

#define planet_width 30
#define planet_height 30

#define mplanet_width 16
#define mplanet_height 16

#define shield_width 20
#define shield_height 20

#define icon_width 64
#define icon_height 64
extern char icon_bits[];

#define stipple_width 16
#define stipple_height 16
extern char stipple_bits[];

