# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.51 89/12/12 12:37:30 jim Exp $
#
# The cpp used on this machine replaces all newlines and multiple tabs and
# spaces in a macro expansion with a single space.  Imake tries to compensate
# for this, but is not always successful.
#

###########################################################################
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $XConsortium: Imake.tmpl,v 1.77 89/12/18 17:01:37 jim Exp $
#
# Platform-specific parameters may be set in the appropriate .cf
# configuration files.  Site-wide parameters may be set in the file
# site.def.  Full rebuilds are recommended if any parameters are changed.
#
# If your C preprocessor doesn't define any unique symbols, you'll need
# to set BOOTSTRAPCFLAGS when rebuilding imake (usually when doing
# "make Makefile", "make Makefiles", or "make World").
#
# If you absolutely can't get imake to work, you'll need to set the
# variables at the top of each Makefile as well as the dependencies at the
# bottom (makedepend will do this automatically).
#

###########################################################################
# platform-specific configuration parameters - edit sun.cf to change

# platform:  $XConsortium: sun.cf,v 1.38 89/12/23 16:10:10 jim Exp $
# operating system:  SunOS 4.1

###########################################################################
# site-specific configuration parameters - edit site.def to change

# site:  $XConsortium: site.def,v 1.21 89/12/06 11:46:50 jim Exp $

            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

               AR = ar cq
  BOOTSTRAPCFLAGS =
               CC = cc

         COMPRESS = compress
              CPP = /lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = cc -E $(STD_CPP_DEFINES)
          INSTALL = install
               LD = ld
             LINT = lint
      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv
               CP = cp
           RANLIB = ranlib
  RANLIBINSTFLAGS =
               RM = rm -f
     STD_INCLUDES =
  STD_CPP_DEFINES =
      STD_DEFINES =
 EXTRA_LOAD_FLAGS =
  EXTRA_LIBRARIES =
             TAGS = ctags

    SHAREDCODEDEF = -DSHAREDCODE
         SHLIBDEF = -DSUNSHLIB

    PROTO_DEFINES =

     INSTPGMFLAGS =

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4755
     INSTLIBFLAGS = -m 0664
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4755

          DESTDIR =

     TOP_INCLUDES = -I$(INCROOT)

      CDEBUGFLAGS = -O
        CCOPTIONS = -n
      COMPATFLAGS = -DXAW_BC

      ALLINCLUDES = $(STD_INCLUDES) $(TOP_INCLUDES) $(INCLUDES) $(EXTRA_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(PROTO_DEFINES) $(DEFINES) $(COMPATFLAGS)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES)
           LDLIBS = $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)
   LDCOMBINEFLAGS = -X -r

        MACROFILE = sun.cf
           RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/Imake.rules \
			$(IRULESRC)/Project.tmpl $(IRULESRC)/site.def \
			$(IRULESRC)/$(MACROFILE) $(EXTRA_ICONFIGFILES)

###########################################################################
# X Window System Build Parameters
# $XConsortium: Project.tmpl,v 1.63 89/12/18 16:46:44 jim Exp $

###########################################################################
# X Window System make variables; this need to be coordinated with rules
# $XConsortium: Project.tmpl,v 1.63 89/12/18 16:46:44 jim Exp $

          PATHSEP = /
        USRLIBDIR = $(DESTDIR)/usr/lib
           BINDIR = $(DESTDIR)/usr/bin/X11
          INCROOT = $(DESTDIR)/usr/include
     BUILDINCROOT = $(TOP)
      BUILDINCDIR = $(BUILDINCROOT)/X11
      BUILDINCTOP = ..
           INCDIR = $(INCROOT)/X11
           ADMDIR = $(DESTDIR)/usr/adm
           LIBDIR = $(USRLIBDIR)/X11
        CONFIGDIR = $(LIBDIR)/config
       LINTLIBDIR = $(USRLIBDIR)/lint

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
           AWMDIR = $(LIBDIR)/awm
           TWMDIR = $(LIBDIR)/twm
           GWMDIR = $(LIBDIR)/gwm
          MANPATH = $(DESTDIR)/usr/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)n
        LIBMANDIR = $(MANSOURCEPATH)3
      XAPPLOADDIR = $(LIBDIR)/app-defaults

        SOXLIBREV = 4.2
          SOXTREV = 4.0
         SOXAWREV = 4.0
        SOOLDXREV = 4.0
         SOXMUREV = 4.0
        SOXEXTREV = 4.0

       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

            IMAKE = imake
           DEPEND = makedepend
              RGB = rgb
            FONTC = bdftosnf
        MKFONTDIR = mkfontdir
        MKDIRHIER = /bin/sh $(BINDIR)/mkdirhier.sh

        CONFIGSRC = $(TOP)/config
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
           LIBSRC = $(TOP)/lib
          FONTSRC = $(TOP)/fonts
       INCLUDESRC = $(TOP)/X11
        SERVERSRC = $(TOP)/server
          UTILSRC = $(TOP)/util
        SCRIPTSRC = $(UTILSRC)/scripts
       EXAMPLESRC = $(TOP)/examples
       CONTRIBSRC = $(TOP)/../contrib
           DOCSRC = $(TOP)/doc
           RGBSRC = $(TOP)/rgb
        DEPENDSRC = $(UTILSRC)/makedepend
         IMAKESRC = $(CONFIGSRC)
         XAUTHSRC = $(LIBSRC)/Xau
          XLIBSRC = $(LIBSRC)/X
           XMUSRC = $(LIBSRC)/Xmu
       TOOLKITSRC = $(LIBSRC)/Xt
       AWIDGETSRC = $(LIBSRC)/Xaw
       OLDXLIBSRC = $(LIBSRC)/oldX
      XDMCPLIBSRC = $(LIBSRC)/Xdmcp
      BDFTOSNFSRC = $(FONTSRC)/bdftosnf
     MKFONTDIRSRC = $(FONTSRC)/mkfontdir
     EXTENSIONSRC = $(TOP)/extensions

  DEPEXTENSIONLIB = $(USRLIBDIR)/libXext.a
     EXTENSIONLIB =  -lXext

          DEPXLIB = $(DEPEXTENSIONLIB)
             XLIB = $(EXTENSIONLIB) -lX11

      DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
         XAUTHLIB =  -lXau

        DEPXMULIB =
           XMULIB = -lXmu

       DEPOLDXLIB =
          OLDXLIB = -loldX

      DEPXTOOLLIB =
         XTOOLLIB = -lXt

        DEPXAWLIB =
           XAWLIB = -lXaw

 LINTEXTENSIONLIB = $(USRLIBDIR)/llib-lXext.ln
         LINTXLIB = $(USRLIBDIR)/llib-lX11.ln
          LINTXMU = $(USRLIBDIR)/llib-lXmu.ln
        LINTXTOOL = $(USRLIBDIR)/llib-lXt.ln
          LINTXAW = $(USRLIBDIR)/llib-lXaw.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)

###########################################################################
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $XConsortium: Imake.rules,v 1.67 89/12/18 17:14:15 jim Exp $

###########################################################################
# start of Imakefile

       XTREKD = in.xtrekd

     XTREKDIR = /usr/lib/X11/xtrek
      DEFINES = -DNEWINET -DSUN40 -DCUSTOMSHIP -DEXCLUDE -DNDBM
     LOCALINC = bitmaps.h data.h defs.h planets.h struct.h xtrekfont.h \
                clock.bitmap
        SRCS1 = bitmaps.c colors.c coup.c data.c death.c detonate.c dmessage.c \
                enter.c getship.c inform.c input.c interface.c main.c \
                newwin.c orbit.c phaser.c planetlist.c playerlist.c \
                pstats.c redraw.c smessage.c subdaemon.c stats.c torp.c \
                util.c warning.c random.c rmove.c scorelist.c \
                trigtab.c itoa.c minisubs.c war.c DBG.c
        OBJS1 = bitmaps.o colors.o coup.o data.o death.o detonate.o dmessage.o \
                enter.o getship.o inform.o input.o interface.o main.o \
                newwin.o orbit.o phaser.o planetlist.o playerlist.o \
                pstats.o redraw.o smessage.o subdaemon.o stats.o torp.o \
                util.o warning.o random.o rmove.o scorelist.o \
                trigtab.o itoa.o minisubs.o war.o DBG.o
    LINTFILES = bitmaps.ln colors.ln coup.ln data.ln death.ln detonate.ln \
                dmessage.ln enter.ln getship.ln inform.ln input.ln \
                interface.ln main.ln newwin.ln orbit.ln phaser.ln \
                planetlist.ln playerlist.ln pstats.ln redraw.ln smessage.ln \
                subdaemon.ln stats.ln torp.ln util.ln warning.ln random.ln \
                rmove.ln scorelist.ln trigtab.ln itoa.ln minisubs.ln \
                war.ln DBG.ln
        SRCS2 = xtrek.c
        OBJS2 = xtrek.o
        SRCS3 = xtrekb.c
        OBJS3 = xtrekb.o
         SRCS = $(SRCS1) $(SRCS2) $(SRCS3)
        SRCSF = xtrek.bdf
        OBJSF = xtrek.snf
         OBJS = $(OBJSF)
     PROGRAMS = bitmaps.h xtrek $(XTREKD) xtrekb
     INCLUDES = -I$(TOP)
     LINTOPTS = -iabchu
         LIBS = -ldbm -Bstatic $(XLIB) -lm
           FC = bdftosnf

.SUFFIXES: .ln

all:: $(PROGRAMS)

xtrek: $(OBJS2)
	$(RM) $@
	$(CC) -o $@ $(OBJS2) $(LDOPTIONS)  $(LDLIBS) -ldbm -Bstatic $(EXTRA_LOAD_FLAGS)

clean::
	$(RM) xtrek

$(XTREKD): $(OBJS1)
	$(RM) $@
	$(CC) -o $@ $(OBJS1) $(LDOPTIONS)  $(LDLIBS) $(LIBS) $(EXTRA_LOAD_FLAGS)

clean::
	$(RM) $(XTREKD)

xtrekb: $(OBJS3)
	$(RM) $@
	$(CC) -o $@ $(OBJS3) $(LDOPTIONS)  $(LDLIBS) $(LIBS) $(EXTRA_LOAD_FLAGS)

clean::
	$(RM) xtrekb

all:: $(OBJS) fonts.dir

fonts.dir: $(OBJS)
	$(MKFONTDIR) .

clean::
	$(RM) *.snf fonts.dir

xtrek.snf: xtrek.bdf
	$(FONTC) $(FONTCFLAGS) $? >$@

all:: $(OBJSF)

depend::
	$(DEPEND) -s "# DO NOT DELETE" -- $(ALLDEFINES) -- $(SRCS)

install:: $(XTREKD)
	$(INSTALL) -c $(INSTPGMFLAGS)   $(XTREKD) $(XTREKDIR)

install:: xtrek
	$(INSTALL) -c $(INSTPGMFLAGS)   xtrek $(BINDIR)

install:: xtrekb
	$(INSTALL) -c $(INSTPGMFLAGS)   xtrekb $(BINDIR)

install.man:: xtrek.man
	$(INSTALL) -c $(INSTMANFLAGS) xtrek.man $(MANDIR)/xtrek.n

install.man:: xtrekb.man
	$(INSTALL) -c $(INSTMANFLAGS) xtrekb.man $(MANDIR)/xtrekb.n

install.man:: xtrek_ship.man
	$(INSTALL) -c $(INSTMANFLAGS) xtrek_ship.man $(MANDIR)/xtrek_ship.n

install:: $(OBJS)
	@case '${MFLAGS}' in *[i]*) set +e;; esac; \
	for i in $(OBJS); do \
	(set -x; $(INSTALL) -c $(INSTDATFLAGS) $$i $(XTREKDIR)); \
	done

install:: fonts.dir
	$(INSTALL) -c $(INSTDATFLAGS) fonts.dir $(XTREKDIR)

bitmaps.h:   bitmaps.c
	sed -e '1i\
		/* DO NOT EDIT THIS FILE. It is machine generated. */'\
	    -e 's/[ 	]*=[ 	]*{[ 	]*$$/;\
		%MARKTEXT%/'\
	    bitmaps.c |\
	sed -e 's/^char/extern char/'\
	    -e 's/^Pixmap/extern Pixmap/'\
	    -e '/[ 	]*%MARKTEXT%[ 	]*$$/,/[ 	]*}[ 	]*;[ 	]*$$/d'\
	    > bitmaps.h

install::
	-mkdir $(XTREKDIR)
	touch $(XTREKDIR)/planets $(XTREKDIR)/motd
	touch $(XTREKDIR)/scores.dir $(XTREKDIR)/scores.pag
	chmod 600 $(XTREKDIR)/planets $(XTREKDIR)/motd
	chmod 644 $(XTREKDIR)/scores.dir $(XTREKDIR)/scores.pag
	chmod u+s $(XTREKDIR)/$(XTREKD)
	-chmod u+w $(XTREKDIR)/xtrek.doc
	-cp doc $(XTREKDIR)/xtrek.doc
	chmod 444 $(XTREKDIR)/xtrek.doc

	-(convertfont xtrek.bdf; bldfamily)
	-cp xtrek.ff xtrek31.fb Families.list Synonyms.list $(XTREKDIR)
	-chmod 444 $(XTREKDIR)/xtrek.ff $(XTREKDIR)/xtrek31.fb
	-chmod 444 $(XTREKDIR)/Families.list $(XTREKDIR)/Synonyms.list

lint: $(LINTFILES)
	$(LINT) $(LINTXLIB) *.ln > xtrek.lint 2>&1

kludge.X11.a:	/usr/lib/libX11.a
	cp /usr/lib/libX11.a kludge.libX11.a	# Copy X11 lib
	chmod u+w kludge.libX11.a		# make our copy writeable
	ar xv kludge.libX11.a Berklib.o		# Copy offending module
	ld -r -o templib.o -h bcopy -h random -h srandom Berklib.o # Hide syms
	ar dv kludge.libX11.a Berklib.o		# Remove offending module
	ar rv kludge.libX11.a templib.o		# Add fixed module
	/bin/rm templib.o			# Remove temp file

shar:
	makekit -s50k -oMANIFEST READ* INSTALL* TODO xtrek.man xtrek_ship.man xtrekb.man Imakefile Makefile doc *.h *.c xtrek.bdf clock.bitmap

cpio:
	for i in READ* INSTALL* TODO xtrek.man xtrek_ship.man xtrekb.man Imakefile Makefile doc *.h *.c xtrek.bdf clock.bitmap; do /bin/echo $$i; done | cpio -ocB > xtrek.cpio

tar:
	tar cf xtrek.tar READ* TODO xtrek.man xtrek_ship.man xtrekb.man Imakefile Makefile doc *.h *.c xtrek.bdf clock.bitmap

.c.ln:
	$(LINT) $(LINTFLAGS) $< > $*.p1 2>&1

###########################################################################
# common rules for all Makefiles - do not edit

emptyrule::

clean::
	$(RM_CMD) \#*

Makefile::
	- at if [ -f Makefile ]; then \
	echo "	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak"; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

###########################################################################
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

Makefiles::

includes::

###########################################################################
# dependencies generated by makedepend

